language: python3
env:
- HUGO_VERSION="0.48"
- HUGO_VERSION="0.49"
- HUGO_VERSION="0.49.2"
install:
- wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
- ls
- mv hugo ~/bin/
- npm install -g postcss-cli
- npm install -g autoprefixer
script:
- python -V
- ~/bin/hugo version
- ~/bin/hugo
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_3381ffcb5528_key -iv $encrypted_3381ffcb5528_iv
  -in deploy_key.enc -out deploy_key -d
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub_Token # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: public
  on:
    branch: source

