language: go
install: go get -v github.com/spf13/hugo
## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
script:
- hugo
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_3381ffcb5528_key -iv $encrypted_3381ffcb5528_iv
  -in deploy_key.enc -out deploy_key -d
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
