language: python3
install: 
#- go version
#- go get -v github.com/spf13/hugo
- python3 test/hugo.py
script:
 #- apt-get install libstdc++6
 #- npm install postcss-cli
 #- npm install autoprefixer
 #- ./bin/hugo version
- ./bin/hugo
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_3381ffcb5528_key -iv $encrypted_3381ffcb5528_iv
  -in deploy_key.enc -out deploy_key -d
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub_Token # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: public
  on:
    branch: source

