language: go
go:
  - 1.4
sudo: required
install:
  - sudo pip install Pygments
  - go get github.com/spf13/hugo
script: hugo
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: edgfdgvanbrown.io
  region: us-wes453634t-2
  endpoint: evanbro564564wn.5645757io.s3-website-us-west-2.amazonaws.com
  local-dir: public
  skip_cleanup: true
  on:
    repo: PhilippvK/philippvk.github.io
