language: generic
os: linux
dist: xenial
env:
- HUGO_VERSION="0.49.2"
install:
  - npm install postcss-cli
  - npm install autoprefixer
  - sudo apt-get install -yqq libstdc++6
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
  - rm hugo.deb
script:
- hugo
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_3381ffcb5528_key -iv $encrypted_3381ffcb5528_iv
  -in deploy_key.enc -out deploy_key -d
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  token: $GitHub_Token # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: public
  on:
    branch: source
