baseurl             = "/"
languageCode        = "en-us"
title               = "Phi."
theme               = "introduction"
enforce_ssl         = "philippvk.github.io"
builddrafts         = true # DEBUG
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "x" # Enable Disqus for comments
# googleAnalytics   = "x"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Philipp van Kempen" # Full name shows on blog post pages
firstname     = "Phi" # First name shows in introduction on main page
tagline       = "I'm a programmer and studying Electrical Engineering." # Appears after the introduction
introheight   = "medium" # Input either 'medium' or 'large' or 'fullheight'
avatar        = "img/Scan_Photo.jpg" # Path to image in static folder eg. img/avatar.png 
email         = "phvankempen@googlemail.com" # Shows in contact section, or leave blank to omit
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Philipp van Kempen's"
faviconfile   = "img/logo.png"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "Introduction theme by Vicky Lai for Hugo © Philipp van Kempen - 2017" # Text to show in footer (overrides default text)

# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
linkedin      = "philipp-van-kempen-8628b7124"
twitter       = "phiologe"
github        = "PhilippvK"
codepen       = ""
pinterest     = ""
facebook      = "PhilippvK"
googleplus    = "PhilippvanKempen1"

showblog        = true # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/project1.jpg"
project1title   = "Gadgets"

project2link    = "#"
project2img     = "img/project2.jpg"
project2title   = "Music"

project3link    = "#"
project3img     = "img/project3.jpg"
project3title   = "Electronics"    
