baseurl             = "/"
languageCode        = "en-us"
title               = "Phi."
theme               = "introduction2"
#enforce_ssl         = "philippvk.github.io"
builddrafts         = true # DEBUG
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# TODOL googleAnalytics   = "x"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Philipp van Kempen" # Full name shows on blog post pages
firstname     = "Phi" # First name shows in introduction on main page
tagline       = "I'm a programmer and studying Electrical Engineering." # Appears after the introduction
introheight   = "medium" # Input either 'medium' or 'large' or 'fullheight'
avatar        = "img/Scan_Photo.jpg" # Path to image in static folder eg. img/avatar.png
email         = "phvankempen@googlemail.com" # Shows in contact section, or leave blank to omit
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Philipp van Kempen's"
faviconfile   = "img/logo.png"
highlightjs   = true # Syntax highlighting
lang          = "en"
theme         = "light"
footertext    = "Introduction theme by Vicky Lai for Hugo. Copyright © Philipp van Kempen - 2017" # Text to show in footer (overrides default text)
fadein = true

[[params.social]]
url = "https://twitter.com/phiologe"
icon = "twitter"

[[params.social]]
url = "https://facebook.com/"
icon = "facebook"

[[params.social]]
url = "https://www.xing.com/profile/Philipp_vanKempen"
icon = "xing"

[[params.social]]
url = "https://www.linkedin.com/in/philipp-van-kempen-8628b7124/"
icon = "linkedin"

[[params.social]]
url = "https://github.com/PhilippvK"
icon = "github"

[[params.social]]
url = "https://plus.google.com/u/0/+PhilippvanKempen1"
icon = "google-plus"

showblog        = true # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/project1.jpg"
project1title   = "Gadgets"

project2link    = "#"
project2img     = "img/project2.jpg"
project2title   = "Music"

project3link    = "#"
project3img     = "img/project3.jpg"
project3title   = "Electronics"
