languageCode = "en-us"
title = "Philipp van Kempen "
baseURL = "https://philippvk.github.io/"
theme="cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Philipp van Kempen"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"
[params]
  Author = "Philipp van Kempen"
  description = "I <3 making web sites"
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 MST"
  copyright = "Copyright © 2017 Philipp van Kempen"
  logofile = "img/logo.png"
  faviconfile = "img/logo.png"
  highlightjs = true
  progressively = true
  lang = "en"
  github = "PhilippvK"
  email = "phvankempen@googlemail.com"
  linkedin = "philipp-van-kempen-8628b7124"
  twitter = "phiologe"
  social_banner = "img/banner.jpg"
  posts_navigation = true


[[params.social]]
    title = "twitter"
    url = "https://twitter.com/phiologe"
[[params.social]]
    title = "github"
    url = "https://github.com/PhilippvK"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/philipp-van-kempen-8628b7124/"
